name: bridge_generator
description: Generates Chimera Bridge code for RN (Turbo) -> Native -> Flutter.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mason: ^0.1.0
  path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.0
  mason_cli: ^0.1.0